import express from "express";
import fs from "fs";
import path from "path";
import { JSONWritable } from "../jsonWritable.js";

export interface CameraState {
  pan: { x: number; y: number };
  zoom: number;
  rotate: { azimuth: number; elevation: number };
}

export class Camera extends JSONWritable {
  // Shared WSL path visible to both Windows and Ubuntu
  protected filePath =
  "\\\\wsl$\\Ubuntu-24.04\\home\\muziba\\vulkan_testing\\muziba_share\\camera.json";

  private _pan: { x: number; y: number };
  private _zoom: number;
  private _rotate: { azimuth: number; elevation: number };

  constructor(
    panX: number,
    panY: number,
    zoom: number,
    azimuth: number,
    elevation: number
  ) {
    super();

    this._pan = { x: panX, y: panY };
    this._zoom = zoom;
    this._rotate = {
      azimuth,
      elevation,
    };
  }

  getKey(): string {
    return "camera";
  }

  toJSON(): CameraState {
    return {
      pan: this._pan,
      zoom: this._zoom,
      rotate: this._rotate,
    };
  }

  getState(): CameraState {
    return this.toJSON();
  }
}

const cameraRouter = express.Router();

/**
 * POST /camera
 * Receives camera updates from canvas
 * Writes camera.json into the shared WSL folder
 */
cameraRouter.post("/", (req, res) => {
  try {
    const { pan, zoom, rotate } = req.body;

    if (
      pan?.x == null ||
      pan?.y == null ||
      zoom == null ||
      rotate?.azimuth == null ||
      rotate?.elevation == null
    ) {
      res.status(400).json({
        success: false,
        error: "Missing camera fields",
      });
      return;
    }

    const camera = new Camera(
      Number(pan.x),
      Number(pan.y),
      Number(zoom),
      Number(rotate.azimuth),
      Number(rotate.elevation)
    );

    camera.write();

    res.set("Cache-Control", "no-store");

    res.json({
      success: true,
      message: "Camera state updated",
    });
  } catch (error) {
    console.error("[camera] write failed:", error);

    res.status(500).json({
      success: false,
      error: (error as Error).message,
    });
  }
});

/**
 * GET /camera/output.jpeg
 * Serves image generated by RenderEngine
 */
cameraRouter.get("/output.jpeg", (req, res) => {
  const outputPath =
  "\\\\wsl$\\Ubuntu-24.04\\home\\muziba\\vulkan_testing\\muziba_share\\output.jpeg";

  if (!fs.existsSync(outputPath)) {
    res.status(404).json({
      success: false,
      error: "output.jpeg not found",
    });
    return;
  }

  res.set({
    "Cache-Control": "no-store",
    Pragma: "no-cache",
    Expires: "0",
  });

  res.sendFile(path.resolve(outputPath));
});

export default cameraRouter;