import express from "express";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import jsonWriter from "../base/jsonWriter.js";
import { createGrpcClient } from "../base/grpcClient.js";
//import { grpcClientCamera } from "../grpc/grpcClientCamera.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);


export interface CameraState {
  pan: { x: number; y: number };
  zoom: number;
  rotate: { azimuth: number; elevation: number };
}


export class Camera {

  private _name: string;
  private _outputFilePath: string;
  private _pan: { x: number; y: number };
  private _zoom: number;
  private _rotate: { azimuth: number; elevation: number };

  constructor(name: string, panX: number, panY: number, zoom: number, azimuth: number, elevation: number) {
    this._name = name;
    this._outputFilePath = path.join(__dirname, "../../clientInput/", this._name + ".json");
    this._pan = { x: panX, y: panY };
    this._zoom = zoom;
    this._rotate = {
      azimuth,
      elevation,
    };
  }

  setState(panX: number, panY: number, zoom: number, azimuth: number, elevation: number) {
    this._pan = { x: panX, y: panY };
    this._zoom = zoom;
    this._rotate = {
      azimuth,
      elevation,
    };
  }

  toJSON(): CameraState {
    return {
      pan: this._pan,
      zoom: this._zoom,
      rotate: this._rotate,
    };
  }

  getPath(): string {
    return this._outputFilePath;
  }
}


// This is the camera of the main/central canvas
class CentralCameraManager {
  private _camera: Camera;
  private _grpc: ReturnType<typeof createGrpcClient>;

  constructor() {
    this._camera = new Camera("centralCamera", 0, 0, 1, 0, 0);
    this._grpc = createGrpcClient(
      path.join(__dirname, "proto", "camera.proto"),
      "camera.CameraService",
      "localhost:50051"
    );
  }

  updateState(panX: number, panY: number, zoom: number, azimuth: number, elevation: number) {
    this._camera.setState(panX, panY, zoom, azimuth, elevation);

    // Write state to JSON on background thread
    //jsonWriter.postMessage({ type: "keyValue", key: "camera", data: this._camera.toJSON(),
    //                       filePath: this._camera.getPath() });

    // Forward state to gRPC server
    this._grpc.call("UpdateCamera", { panX, panY, zoom, azimuth, elevation })
      .catch((err: Error) => console.error("[camera] gRPC error:", err));
  }
}


const centralCameraManager = new CentralCameraManager();


const cameraRouter = express.Router();

/**
 * The post method for the camera class. The data coming in is used to update the
 * camera object. This notifies a worker thread which writes the camera state to a JSON file.
 *
 * Curl test by: 
 * curl -X POST http://localhost:4000/camera/ -H "Content-Type: application/json" -d '{"pan": {"x":1,"y":1}, "zoom": 1, "rotate": {"azimuth": 1, "elevation": 1}}'
 */
cameraRouter.post("/", (req, res) => {
  try {
    const { pan, zoom, rotate } = req.body;

    if (pan?.x == null || pan?.y == null || zoom == null || rotate?.azimuth == null
                                                         || rotate?.elevation == null) {
      res.status(400).json({
        success: false,
        error: "Camera state missing.",
      });
      return;
    }

    // Update the central camera manager — JSON write happens on a background worker thread
    centralCameraManager.updateState(Number(pan.x), Number(pan.y), Number(zoom),
                                     Number(rotate.azimuth), Number(rotate.elevation)
                                    );

    res.json({
       success: true,
       message: "Camera state updated.",
    });
  } catch (error) {
    console.error("Camera write/update failed:", error);

    res.status(500).json({
      success: false,
      error: (error as Error).message,
    });
  }
});

/**
 * GET /camera/output.jpeg
 * Serves image generated by RenderEngine
 */
cameraRouter.get("/output.jpeg", (req, res) => {
  const outputPath =
  "\\\\wsl$\\Ubuntu-24.04\\home\\muziba\\vulkan_testing\\muziba_share\\output.jpeg";

  if (!fs.existsSync(outputPath)) {
    res.status(404).json({
      success: false,
      error: "output.jpeg not found",
    });
    return;
  }

  // Set headers to prevent caching by the browser
  res.set({
    "Cache-Control": "no-store",
    Pragma: "no-cache",
    Expires: "0",
  });

  res.sendFile(path.resolve(outputPath));
});

export default cameraRouter;